// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto

#include "inference.pb.h"
#include "inference.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace inference {

static const char* InferenceService_method_names[] = {
  "/inference.InferenceService/DescribeImage",
  "/inference.InferenceService/Chat",
};

std::unique_ptr< InferenceService::Stub> InferenceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InferenceService::Stub> stub(new InferenceService::Stub(channel, options));
  return stub;
}

InferenceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_DescribeImage_(InferenceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Chat_(InferenceService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status InferenceService::Stub::DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::inference::DescribeImageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::inference::DescribeImageRequest, ::inference::DescribeImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DescribeImage_, context, request, response);
}

void InferenceService::Stub::async::DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::inference::DescribeImageRequest, ::inference::DescribeImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DescribeImage_, context, request, response, std::move(f));
}

void InferenceService::Stub::async::DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DescribeImage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::inference::DescribeImageResponse>* InferenceService::Stub::PrepareAsyncDescribeImageRaw(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::inference::DescribeImageResponse, ::inference::DescribeImageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DescribeImage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::inference::DescribeImageResponse>* InferenceService::Stub::AsyncDescribeImageRaw(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDescribeImageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::inference::ChatResponse>* InferenceService::Stub::ChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::inference::ChatResponse>::Create(channel_.get(), rpcmethod_Chat_, context, request);
}

void InferenceService::Stub::async::Chat(::grpc::ClientContext* context, const ::inference::ChatRequest* request, ::grpc::ClientReadReactor< ::inference::ChatResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::inference::ChatResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Chat_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::inference::ChatResponse>* InferenceService::Stub::AsyncChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::inference::ChatResponse>::Create(channel_.get(), cq, rpcmethod_Chat_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::inference::ChatResponse>* InferenceService::Stub::PrepareAsyncChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::inference::ChatResponse>::Create(channel_.get(), cq, rpcmethod_Chat_, context, request, false, nullptr);
}

InferenceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InferenceService::Service, ::inference::DescribeImageRequest, ::inference::DescribeImageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InferenceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inference::DescribeImageRequest* req,
             ::inference::DescribeImageResponse* resp) {
               return service->DescribeImage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InferenceService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< InferenceService::Service, ::inference::ChatRequest, ::inference::ChatResponse>(
          [](InferenceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::inference::ChatRequest* req,
             ::grpc::ServerWriter<::inference::ChatResponse>* writer) {
               return service->Chat(ctx, req, writer);
             }, this)));
}

InferenceService::Service::~Service() {
}

::grpc::Status InferenceService::Service::DescribeImage(::grpc::ServerContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InferenceService::Service::Chat(::grpc::ServerContext* context, const ::inference::ChatRequest* request, ::grpc::ServerWriter< ::inference::ChatResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace inference

