// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto
#ifndef GRPC_inference_2eproto__INCLUDED
#define GRPC_inference_2eproto__INCLUDED

#include "inference.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace inference {

class InferenceService final {
 public:
  static constexpr char const* service_full_name() {
    return "inference.InferenceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::inference::DescribeImageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inference::DescribeImageResponse>> AsyncDescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inference::DescribeImageResponse>>(AsyncDescribeImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inference::DescribeImageResponse>> PrepareAsyncDescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inference::DescribeImageResponse>>(PrepareAsyncDescribeImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::inference::ChatResponse>> Chat(::grpc::ClientContext* context, const ::inference::ChatRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::inference::ChatResponse>>(ChatRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::inference::ChatResponse>> AsyncChat(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::inference::ChatResponse>>(AsyncChatRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::inference::ChatResponse>> PrepareAsyncChat(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::inference::ChatResponse>>(PrepareAsyncChatRaw(context, request, cq));
    }
    // Streaming response for real-time token generation
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Chat(::grpc::ClientContext* context, const ::inference::ChatRequest* request, ::grpc::ClientReadReactor< ::inference::ChatResponse>* reactor) = 0;
      // Streaming response for real-time token generation
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inference::DescribeImageResponse>* AsyncDescribeImageRaw(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inference::DescribeImageResponse>* PrepareAsyncDescribeImageRaw(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::inference::ChatResponse>* ChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::inference::ChatResponse>* AsyncChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::inference::ChatResponse>* PrepareAsyncChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::inference::DescribeImageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inference::DescribeImageResponse>> AsyncDescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inference::DescribeImageResponse>>(AsyncDescribeImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inference::DescribeImageResponse>> PrepareAsyncDescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inference::DescribeImageResponse>>(PrepareAsyncDescribeImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::inference::ChatResponse>> Chat(::grpc::ClientContext* context, const ::inference::ChatRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::inference::ChatResponse>>(ChatRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::inference::ChatResponse>> AsyncChat(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::inference::ChatResponse>>(AsyncChatRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::inference::ChatResponse>> PrepareAsyncChat(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::inference::ChatResponse>>(PrepareAsyncChatRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response, std::function<void(::grpc::Status)>) override;
      void DescribeImage(::grpc::ClientContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Chat(::grpc::ClientContext* context, const ::inference::ChatRequest* request, ::grpc::ClientReadReactor< ::inference::ChatResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::inference::DescribeImageResponse>* AsyncDescribeImageRaw(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inference::DescribeImageResponse>* PrepareAsyncDescribeImageRaw(::grpc::ClientContext* context, const ::inference::DescribeImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::inference::ChatResponse>* ChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request) override;
    ::grpc::ClientAsyncReader< ::inference::ChatResponse>* AsyncChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::inference::ChatResponse>* PrepareAsyncChatRaw(::grpc::ClientContext* context, const ::inference::ChatRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DescribeImage_;
    const ::grpc::internal::RpcMethod rpcmethod_Chat_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DescribeImage(::grpc::ServerContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response);
    virtual ::grpc::Status Chat(::grpc::ServerContext* context, const ::inference::ChatRequest* request, ::grpc::ServerWriter< ::inference::ChatResponse>* writer);
    // Streaming response for real-time token generation
  };
  template <class BaseClass>
  class WithAsyncMethod_DescribeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DescribeImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DescribeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DescribeImage(::grpc::ServerContext* /*context*/, const ::inference::DescribeImageRequest* /*request*/, ::inference::DescribeImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDescribeImage(::grpc::ServerContext* context, ::inference::DescribeImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::inference::DescribeImageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Chat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Chat() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Chat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Chat(::grpc::ServerContext* /*context*/, const ::inference::ChatRequest* /*request*/, ::grpc::ServerWriter< ::inference::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestChat(::grpc::ServerContext* context, ::inference::ChatRequest* request, ::grpc::ServerAsyncWriter< ::inference::ChatResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DescribeImage<WithAsyncMethod_Chat<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DescribeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DescribeImage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::inference::DescribeImageRequest, ::inference::DescribeImageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inference::DescribeImageRequest* request, ::inference::DescribeImageResponse* response) { return this->DescribeImage(context, request, response); }));}
    void SetMessageAllocatorFor_DescribeImage(
        ::grpc::MessageAllocator< ::inference::DescribeImageRequest, ::inference::DescribeImageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::inference::DescribeImageRequest, ::inference::DescribeImageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DescribeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DescribeImage(::grpc::ServerContext* /*context*/, const ::inference::DescribeImageRequest* /*request*/, ::inference::DescribeImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DescribeImage(
      ::grpc::CallbackServerContext* /*context*/, const ::inference::DescribeImageRequest* /*request*/, ::inference::DescribeImageResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Chat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Chat() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::inference::ChatRequest, ::inference::ChatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inference::ChatRequest* request) { return this->Chat(context, request); }));
    }
    ~WithCallbackMethod_Chat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Chat(::grpc::ServerContext* /*context*/, const ::inference::ChatRequest* /*request*/, ::grpc::ServerWriter< ::inference::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::inference::ChatResponse>* Chat(
      ::grpc::CallbackServerContext* /*context*/, const ::inference::ChatRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_DescribeImage<WithCallbackMethod_Chat<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DescribeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DescribeImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DescribeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DescribeImage(::grpc::ServerContext* /*context*/, const ::inference::DescribeImageRequest* /*request*/, ::inference::DescribeImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Chat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Chat() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Chat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Chat(::grpc::ServerContext* /*context*/, const ::inference::ChatRequest* /*request*/, ::grpc::ServerWriter< ::inference::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DescribeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DescribeImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DescribeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DescribeImage(::grpc::ServerContext* /*context*/, const ::inference::DescribeImageRequest* /*request*/, ::inference::DescribeImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDescribeImage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Chat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Chat() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Chat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Chat(::grpc::ServerContext* /*context*/, const ::inference::ChatRequest* /*request*/, ::grpc::ServerWriter< ::inference::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestChat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DescribeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DescribeImage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DescribeImage(context, request, response); }));
    }
    ~WithRawCallbackMethod_DescribeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DescribeImage(::grpc::ServerContext* /*context*/, const ::inference::DescribeImageRequest* /*request*/, ::inference::DescribeImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DescribeImage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Chat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Chat() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Chat(context, request); }));
    }
    ~WithRawCallbackMethod_Chat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Chat(::grpc::ServerContext* /*context*/, const ::inference::ChatRequest* /*request*/, ::grpc::ServerWriter< ::inference::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Chat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DescribeImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DescribeImage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::inference::DescribeImageRequest, ::inference::DescribeImageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::inference::DescribeImageRequest, ::inference::DescribeImageResponse>* streamer) {
                       return this->StreamedDescribeImage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DescribeImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DescribeImage(::grpc::ServerContext* /*context*/, const ::inference::DescribeImageRequest* /*request*/, ::inference::DescribeImageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDescribeImage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::inference::DescribeImageRequest,::inference::DescribeImageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DescribeImage<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Chat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Chat() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::inference::ChatRequest, ::inference::ChatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::inference::ChatRequest, ::inference::ChatResponse>* streamer) {
                       return this->StreamedChat(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Chat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Chat(::grpc::ServerContext* /*context*/, const ::inference::ChatRequest* /*request*/, ::grpc::ServerWriter< ::inference::ChatResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedChat(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::inference::ChatRequest,::inference::ChatResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Chat<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_DescribeImage<WithSplitStreamingMethod_Chat<Service > > StreamedService;
};

}  // namespace inference


#endif  // GRPC_inference_2eproto__INCLUDED
