// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: crawler.proto

#include "crawler.pb.h"
#include "crawler.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace crawler {

static const char* CrawlerService_method_names[] = {
  "/crawler.CrawlerService/IndexPage",
};

std::unique_ptr< CrawlerService::Stub> CrawlerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CrawlerService::Stub> stub(new CrawlerService::Stub(channel, options));
  return stub;
}

CrawlerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_IndexPage_(CrawlerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CrawlerService::Stub::IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::crawler::IndexPageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::crawler::IndexPageRequest, ::crawler::IndexPageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_IndexPage_, context, request, response);
}

void CrawlerService::Stub::async::IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::crawler::IndexPageRequest, ::crawler::IndexPageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IndexPage_, context, request, response, std::move(f));
}

void CrawlerService::Stub::async::IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IndexPage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::crawler::IndexPageResponse>* CrawlerService::Stub::PrepareAsyncIndexPageRaw(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::crawler::IndexPageResponse, ::crawler::IndexPageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_IndexPage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::crawler::IndexPageResponse>* CrawlerService::Stub::AsyncIndexPageRaw(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIndexPageRaw(context, request, cq);
  result->StartCall();
  return result;
}

CrawlerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CrawlerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CrawlerService::Service, ::crawler::IndexPageRequest, ::crawler::IndexPageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CrawlerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::crawler::IndexPageRequest* req,
             ::crawler::IndexPageResponse* resp) {
               return service->IndexPage(ctx, req, resp);
             }, this)));
}

CrawlerService::Service::~Service() {
}

::grpc::Status CrawlerService::Service::IndexPage(::grpc::ServerContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace crawler

