// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crawler.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_crawler_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_crawler_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_crawler_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_crawler_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_crawler_2eproto;
namespace crawler {
class ImageInfo;
struct ImageInfoDefaultTypeInternal;
extern ImageInfoDefaultTypeInternal _ImageInfo_default_instance_;
class IndexPageRequest;
struct IndexPageRequestDefaultTypeInternal;
extern IndexPageRequestDefaultTypeInternal _IndexPageRequest_default_instance_;
class IndexPageResponse;
struct IndexPageResponseDefaultTypeInternal;
extern IndexPageResponseDefaultTypeInternal _IndexPageResponse_default_instance_;
}  // namespace crawler
PROTOBUF_NAMESPACE_OPEN
template<> ::crawler::ImageInfo* Arena::CreateMaybeMessage<::crawler::ImageInfo>(Arena*);
template<> ::crawler::IndexPageRequest* Arena::CreateMaybeMessage<::crawler::IndexPageRequest>(Arena*);
template<> ::crawler::IndexPageResponse* Arena::CreateMaybeMessage<::crawler::IndexPageResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace crawler {

// ===================================================================

class IndexPageRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crawler.IndexPageRequest) */ {
 public:
  inline IndexPageRequest() : IndexPageRequest(nullptr) {}
  ~IndexPageRequest() override;
  explicit PROTOBUF_CONSTEXPR IndexPageRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IndexPageRequest(const IndexPageRequest& from);
  IndexPageRequest(IndexPageRequest&& from) noexcept
    : IndexPageRequest() {
    *this = ::std::move(from);
  }

  inline IndexPageRequest& operator=(const IndexPageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline IndexPageRequest& operator=(IndexPageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IndexPageRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const IndexPageRequest* internal_default_instance() {
    return reinterpret_cast<const IndexPageRequest*>(
               &_IndexPageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IndexPageRequest& a, IndexPageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(IndexPageRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IndexPageRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IndexPageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IndexPageRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IndexPageRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IndexPageRequest& from) {
    IndexPageRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IndexPageRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crawler.IndexPageRequest";
  }
  protected:
  explicit IndexPageRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImagesFieldNumber = 4,
    kUrlFieldNumber = 1,
    kTitleFieldNumber = 2,
    kRawTextFieldNumber = 3,
  };
  // repeated .crawler.ImageInfo images = 4;
  int images_size() const;
  private:
  int _internal_images_size() const;
  public:
  void clear_images();
  ::crawler::ImageInfo* mutable_images(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crawler::ImageInfo >*
      mutable_images();
  private:
  const ::crawler::ImageInfo& _internal_images(int index) const;
  ::crawler::ImageInfo* _internal_add_images();
  public:
  const ::crawler::ImageInfo& images(int index) const;
  ::crawler::ImageInfo* add_images();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crawler::ImageInfo >&
      images() const;

  // string url = 1;
  void clear_url();
  const std::string& url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_url();
  PROTOBUF_NODISCARD std::string* release_url();
  void set_allocated_url(std::string* url);
  private:
  const std::string& _internal_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_url(const std::string& value);
  std::string* _internal_mutable_url();
  public:

  // string title = 2;
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string raw_text = 3;
  void clear_raw_text();
  const std::string& raw_text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_raw_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_raw_text();
  PROTOBUF_NODISCARD std::string* release_raw_text();
  void set_allocated_raw_text(std::string* raw_text);
  private:
  const std::string& _internal_raw_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_raw_text(const std::string& value);
  std::string* _internal_mutable_raw_text();
  public:

  // @@protoc_insertion_point(class_scope:crawler.IndexPageRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crawler::ImageInfo > images_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr url_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr raw_text_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_crawler_2eproto;
};
// -------------------------------------------------------------------

class ImageInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crawler.ImageInfo) */ {
 public:
  inline ImageInfo() : ImageInfo(nullptr) {}
  ~ImageInfo() override;
  explicit PROTOBUF_CONSTEXPR ImageInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ImageInfo(const ImageInfo& from);
  ImageInfo(ImageInfo&& from) noexcept
    : ImageInfo() {
    *this = ::std::move(from);
  }

  inline ImageInfo& operator=(const ImageInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageInfo& operator=(ImageInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImageInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImageInfo* internal_default_instance() {
    return reinterpret_cast<const ImageInfo*>(
               &_ImageInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ImageInfo& a, ImageInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImageInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ImageInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ImageInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ImageInfo& from) {
    ImageInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crawler.ImageInfo";
  }
  protected:
  explicit ImageInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUrlFieldNumber = 1,
    kAltTextFieldNumber = 2,
    kImageDataFieldNumber = 3,
  };
  // string url = 1;
  void clear_url();
  const std::string& url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_url();
  PROTOBUF_NODISCARD std::string* release_url();
  void set_allocated_url(std::string* url);
  private:
  const std::string& _internal_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_url(const std::string& value);
  std::string* _internal_mutable_url();
  public:

  // string alt_text = 2;
  void clear_alt_text();
  const std::string& alt_text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_alt_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_alt_text();
  PROTOBUF_NODISCARD std::string* release_alt_text();
  void set_allocated_alt_text(std::string* alt_text);
  private:
  const std::string& _internal_alt_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_alt_text(const std::string& value);
  std::string* _internal_mutable_alt_text();
  public:

  // bytes image_data = 3;
  void clear_image_data();
  const std::string& image_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_data();
  PROTOBUF_NODISCARD std::string* release_image_data();
  void set_allocated_image_data(std::string* image_data);
  private:
  const std::string& _internal_image_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_data(const std::string& value);
  std::string* _internal_mutable_image_data();
  public:

  // @@protoc_insertion_point(class_scope:crawler.ImageInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr url_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr alt_text_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_crawler_2eproto;
};
// -------------------------------------------------------------------

class IndexPageResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crawler.IndexPageResponse) */ {
 public:
  inline IndexPageResponse() : IndexPageResponse(nullptr) {}
  ~IndexPageResponse() override;
  explicit PROTOBUF_CONSTEXPR IndexPageResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IndexPageResponse(const IndexPageResponse& from);
  IndexPageResponse(IndexPageResponse&& from) noexcept
    : IndexPageResponse() {
    *this = ::std::move(from);
  }

  inline IndexPageResponse& operator=(const IndexPageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline IndexPageResponse& operator=(IndexPageResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IndexPageResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const IndexPageResponse* internal_default_instance() {
    return reinterpret_cast<const IndexPageResponse*>(
               &_IndexPageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(IndexPageResponse& a, IndexPageResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(IndexPageResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IndexPageResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IndexPageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IndexPageResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IndexPageResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IndexPageResponse& from) {
    IndexPageResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IndexPageResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crawler.IndexPageResponse";
  }
  protected:
  explicit IndexPageResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string error_message = 2;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:crawler.IndexPageResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_crawler_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IndexPageRequest

// string url = 1;
inline void IndexPageRequest::clear_url() {
  _impl_.url_.ClearToEmpty();
}
inline const std::string& IndexPageRequest::url() const {
  // @@protoc_insertion_point(field_get:crawler.IndexPageRequest.url)
  return _internal_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IndexPageRequest::set_url(ArgT0&& arg0, ArgT... args) {
 
 _impl_.url_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:crawler.IndexPageRequest.url)
}
inline std::string* IndexPageRequest::mutable_url() {
  std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:crawler.IndexPageRequest.url)
  return _s;
}
inline const std::string& IndexPageRequest::_internal_url() const {
  return _impl_.url_.Get();
}
inline void IndexPageRequest::_internal_set_url(const std::string& value) {
  
  _impl_.url_.Set(value, GetArenaForAllocation());
}
inline std::string* IndexPageRequest::_internal_mutable_url() {
  
  return _impl_.url_.Mutable(GetArenaForAllocation());
}
inline std::string* IndexPageRequest::release_url() {
  // @@protoc_insertion_point(field_release:crawler.IndexPageRequest.url)
  return _impl_.url_.Release();
}
inline void IndexPageRequest::set_allocated_url(std::string* url) {
  if (url != nullptr) {
    
  } else {
    
  }
  _impl_.url_.SetAllocated(url, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:crawler.IndexPageRequest.url)
}

// string title = 2;
inline void IndexPageRequest::clear_title() {
  _impl_.title_.ClearToEmpty();
}
inline const std::string& IndexPageRequest::title() const {
  // @@protoc_insertion_point(field_get:crawler.IndexPageRequest.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IndexPageRequest::set_title(ArgT0&& arg0, ArgT... args) {
 
 _impl_.title_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:crawler.IndexPageRequest.title)
}
inline std::string* IndexPageRequest::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:crawler.IndexPageRequest.title)
  return _s;
}
inline const std::string& IndexPageRequest::_internal_title() const {
  return _impl_.title_.Get();
}
inline void IndexPageRequest::_internal_set_title(const std::string& value) {
  
  _impl_.title_.Set(value, GetArenaForAllocation());
}
inline std::string* IndexPageRequest::_internal_mutable_title() {
  
  return _impl_.title_.Mutable(GetArenaForAllocation());
}
inline std::string* IndexPageRequest::release_title() {
  // @@protoc_insertion_point(field_release:crawler.IndexPageRequest.title)
  return _impl_.title_.Release();
}
inline void IndexPageRequest::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  _impl_.title_.SetAllocated(title, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.title_.IsDefault()) {
    _impl_.title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:crawler.IndexPageRequest.title)
}

// string raw_text = 3;
inline void IndexPageRequest::clear_raw_text() {
  _impl_.raw_text_.ClearToEmpty();
}
inline const std::string& IndexPageRequest::raw_text() const {
  // @@protoc_insertion_point(field_get:crawler.IndexPageRequest.raw_text)
  return _internal_raw_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IndexPageRequest::set_raw_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.raw_text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:crawler.IndexPageRequest.raw_text)
}
inline std::string* IndexPageRequest::mutable_raw_text() {
  std::string* _s = _internal_mutable_raw_text();
  // @@protoc_insertion_point(field_mutable:crawler.IndexPageRequest.raw_text)
  return _s;
}
inline const std::string& IndexPageRequest::_internal_raw_text() const {
  return _impl_.raw_text_.Get();
}
inline void IndexPageRequest::_internal_set_raw_text(const std::string& value) {
  
  _impl_.raw_text_.Set(value, GetArenaForAllocation());
}
inline std::string* IndexPageRequest::_internal_mutable_raw_text() {
  
  return _impl_.raw_text_.Mutable(GetArenaForAllocation());
}
inline std::string* IndexPageRequest::release_raw_text() {
  // @@protoc_insertion_point(field_release:crawler.IndexPageRequest.raw_text)
  return _impl_.raw_text_.Release();
}
inline void IndexPageRequest::set_allocated_raw_text(std::string* raw_text) {
  if (raw_text != nullptr) {
    
  } else {
    
  }
  _impl_.raw_text_.SetAllocated(raw_text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.raw_text_.IsDefault()) {
    _impl_.raw_text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:crawler.IndexPageRequest.raw_text)
}

// repeated .crawler.ImageInfo images = 4;
inline int IndexPageRequest::_internal_images_size() const {
  return _impl_.images_.size();
}
inline int IndexPageRequest::images_size() const {
  return _internal_images_size();
}
inline void IndexPageRequest::clear_images() {
  _impl_.images_.Clear();
}
inline ::crawler::ImageInfo* IndexPageRequest::mutable_images(int index) {
  // @@protoc_insertion_point(field_mutable:crawler.IndexPageRequest.images)
  return _impl_.images_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crawler::ImageInfo >*
IndexPageRequest::mutable_images() {
  // @@protoc_insertion_point(field_mutable_list:crawler.IndexPageRequest.images)
  return &_impl_.images_;
}
inline const ::crawler::ImageInfo& IndexPageRequest::_internal_images(int index) const {
  return _impl_.images_.Get(index);
}
inline const ::crawler::ImageInfo& IndexPageRequest::images(int index) const {
  // @@protoc_insertion_point(field_get:crawler.IndexPageRequest.images)
  return _internal_images(index);
}
inline ::crawler::ImageInfo* IndexPageRequest::_internal_add_images() {
  return _impl_.images_.Add();
}
inline ::crawler::ImageInfo* IndexPageRequest::add_images() {
  ::crawler::ImageInfo* _add = _internal_add_images();
  // @@protoc_insertion_point(field_add:crawler.IndexPageRequest.images)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crawler::ImageInfo >&
IndexPageRequest::images() const {
  // @@protoc_insertion_point(field_list:crawler.IndexPageRequest.images)
  return _impl_.images_;
}

// -------------------------------------------------------------------

// ImageInfo

// string url = 1;
inline void ImageInfo::clear_url() {
  _impl_.url_.ClearToEmpty();
}
inline const std::string& ImageInfo::url() const {
  // @@protoc_insertion_point(field_get:crawler.ImageInfo.url)
  return _internal_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ImageInfo::set_url(ArgT0&& arg0, ArgT... args) {
 
 _impl_.url_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:crawler.ImageInfo.url)
}
inline std::string* ImageInfo::mutable_url() {
  std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:crawler.ImageInfo.url)
  return _s;
}
inline const std::string& ImageInfo::_internal_url() const {
  return _impl_.url_.Get();
}
inline void ImageInfo::_internal_set_url(const std::string& value) {
  
  _impl_.url_.Set(value, GetArenaForAllocation());
}
inline std::string* ImageInfo::_internal_mutable_url() {
  
  return _impl_.url_.Mutable(GetArenaForAllocation());
}
inline std::string* ImageInfo::release_url() {
  // @@protoc_insertion_point(field_release:crawler.ImageInfo.url)
  return _impl_.url_.Release();
}
inline void ImageInfo::set_allocated_url(std::string* url) {
  if (url != nullptr) {
    
  } else {
    
  }
  _impl_.url_.SetAllocated(url, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:crawler.ImageInfo.url)
}

// string alt_text = 2;
inline void ImageInfo::clear_alt_text() {
  _impl_.alt_text_.ClearToEmpty();
}
inline const std::string& ImageInfo::alt_text() const {
  // @@protoc_insertion_point(field_get:crawler.ImageInfo.alt_text)
  return _internal_alt_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ImageInfo::set_alt_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.alt_text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:crawler.ImageInfo.alt_text)
}
inline std::string* ImageInfo::mutable_alt_text() {
  std::string* _s = _internal_mutable_alt_text();
  // @@protoc_insertion_point(field_mutable:crawler.ImageInfo.alt_text)
  return _s;
}
inline const std::string& ImageInfo::_internal_alt_text() const {
  return _impl_.alt_text_.Get();
}
inline void ImageInfo::_internal_set_alt_text(const std::string& value) {
  
  _impl_.alt_text_.Set(value, GetArenaForAllocation());
}
inline std::string* ImageInfo::_internal_mutable_alt_text() {
  
  return _impl_.alt_text_.Mutable(GetArenaForAllocation());
}
inline std::string* ImageInfo::release_alt_text() {
  // @@protoc_insertion_point(field_release:crawler.ImageInfo.alt_text)
  return _impl_.alt_text_.Release();
}
inline void ImageInfo::set_allocated_alt_text(std::string* alt_text) {
  if (alt_text != nullptr) {
    
  } else {
    
  }
  _impl_.alt_text_.SetAllocated(alt_text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.alt_text_.IsDefault()) {
    _impl_.alt_text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:crawler.ImageInfo.alt_text)
}

// bytes image_data = 3;
inline void ImageInfo::clear_image_data() {
  _impl_.image_data_.ClearToEmpty();
}
inline const std::string& ImageInfo::image_data() const {
  // @@protoc_insertion_point(field_get:crawler.ImageInfo.image_data)
  return _internal_image_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ImageInfo::set_image_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.image_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:crawler.ImageInfo.image_data)
}
inline std::string* ImageInfo::mutable_image_data() {
  std::string* _s = _internal_mutable_image_data();
  // @@protoc_insertion_point(field_mutable:crawler.ImageInfo.image_data)
  return _s;
}
inline const std::string& ImageInfo::_internal_image_data() const {
  return _impl_.image_data_.Get();
}
inline void ImageInfo::_internal_set_image_data(const std::string& value) {
  
  _impl_.image_data_.Set(value, GetArenaForAllocation());
}
inline std::string* ImageInfo::_internal_mutable_image_data() {
  
  return _impl_.image_data_.Mutable(GetArenaForAllocation());
}
inline std::string* ImageInfo::release_image_data() {
  // @@protoc_insertion_point(field_release:crawler.ImageInfo.image_data)
  return _impl_.image_data_.Release();
}
inline void ImageInfo::set_allocated_image_data(std::string* image_data) {
  if (image_data != nullptr) {
    
  } else {
    
  }
  _impl_.image_data_.SetAllocated(image_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.image_data_.IsDefault()) {
    _impl_.image_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:crawler.ImageInfo.image_data)
}

// -------------------------------------------------------------------

// IndexPageResponse

// bool success = 1;
inline void IndexPageResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool IndexPageResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool IndexPageResponse::success() const {
  // @@protoc_insertion_point(field_get:crawler.IndexPageResponse.success)
  return _internal_success();
}
inline void IndexPageResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void IndexPageResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:crawler.IndexPageResponse.success)
}

// string error_message = 2;
inline void IndexPageResponse::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& IndexPageResponse::error_message() const {
  // @@protoc_insertion_point(field_get:crawler.IndexPageResponse.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IndexPageResponse::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:crawler.IndexPageResponse.error_message)
}
inline std::string* IndexPageResponse::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:crawler.IndexPageResponse.error_message)
  return _s;
}
inline const std::string& IndexPageResponse::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void IndexPageResponse::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* IndexPageResponse::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* IndexPageResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:crawler.IndexPageResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void IndexPageResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:crawler.IndexPageResponse.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace crawler

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_crawler_2eproto
