// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: crawler.proto
#ifndef GRPC_crawler_2eproto__INCLUDED
#define GRPC_crawler_2eproto__INCLUDED

#include "crawler.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace crawler {

class CrawlerService final {
 public:
  static constexpr char const* service_full_name() {
    return "crawler.CrawlerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::crawler::IndexPageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::crawler::IndexPageResponse>> AsyncIndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::crawler::IndexPageResponse>>(AsyncIndexPageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::crawler::IndexPageResponse>> PrepareAsyncIndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::crawler::IndexPageResponse>>(PrepareAsyncIndexPageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::crawler::IndexPageResponse>* AsyncIndexPageRaw(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::crawler::IndexPageResponse>* PrepareAsyncIndexPageRaw(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::crawler::IndexPageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::crawler::IndexPageResponse>> AsyncIndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::crawler::IndexPageResponse>>(AsyncIndexPageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::crawler::IndexPageResponse>> PrepareAsyncIndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::crawler::IndexPageResponse>>(PrepareAsyncIndexPageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response, std::function<void(::grpc::Status)>) override;
      void IndexPage(::grpc::ClientContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::crawler::IndexPageResponse>* AsyncIndexPageRaw(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::crawler::IndexPageResponse>* PrepareAsyncIndexPageRaw(::grpc::ClientContext* context, const ::crawler::IndexPageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_IndexPage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status IndexPage(::grpc::ServerContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_IndexPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IndexPage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_IndexPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IndexPage(::grpc::ServerContext* /*context*/, const ::crawler::IndexPageRequest* /*request*/, ::crawler::IndexPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIndexPage(::grpc::ServerContext* context, ::crawler::IndexPageRequest* request, ::grpc::ServerAsyncResponseWriter< ::crawler::IndexPageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_IndexPage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_IndexPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IndexPage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::crawler::IndexPageRequest, ::crawler::IndexPageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::crawler::IndexPageRequest* request, ::crawler::IndexPageResponse* response) { return this->IndexPage(context, request, response); }));}
    void SetMessageAllocatorFor_IndexPage(
        ::grpc::MessageAllocator< ::crawler::IndexPageRequest, ::crawler::IndexPageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::crawler::IndexPageRequest, ::crawler::IndexPageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_IndexPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IndexPage(::grpc::ServerContext* /*context*/, const ::crawler::IndexPageRequest* /*request*/, ::crawler::IndexPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IndexPage(
      ::grpc::CallbackServerContext* /*context*/, const ::crawler::IndexPageRequest* /*request*/, ::crawler::IndexPageResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_IndexPage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_IndexPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IndexPage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_IndexPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IndexPage(::grpc::ServerContext* /*context*/, const ::crawler::IndexPageRequest* /*request*/, ::crawler::IndexPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_IndexPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IndexPage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_IndexPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IndexPage(::grpc::ServerContext* /*context*/, const ::crawler::IndexPageRequest* /*request*/, ::crawler::IndexPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIndexPage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IndexPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IndexPage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->IndexPage(context, request, response); }));
    }
    ~WithRawCallbackMethod_IndexPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IndexPage(::grpc::ServerContext* /*context*/, const ::crawler::IndexPageRequest* /*request*/, ::crawler::IndexPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IndexPage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_IndexPage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_IndexPage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::crawler::IndexPageRequest, ::crawler::IndexPageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::crawler::IndexPageRequest, ::crawler::IndexPageResponse>* streamer) {
                       return this->StreamedIndexPage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_IndexPage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IndexPage(::grpc::ServerContext* /*context*/, const ::crawler::IndexPageRequest* /*request*/, ::crawler::IndexPageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIndexPage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::crawler::IndexPageRequest,::crawler::IndexPageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_IndexPage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_IndexPage<Service > StreamedService;
};

}  // namespace crawler


#endif  // GRPC_crawler_2eproto__INCLUDED
