// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_search_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_search_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_search_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_search_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_search_2eproto;
namespace search {
class SearchRequest;
struct SearchRequestDefaultTypeInternal;
extern SearchRequestDefaultTypeInternal _SearchRequest_default_instance_;
class SearchResponse;
struct SearchResponseDefaultTypeInternal;
extern SearchResponseDefaultTypeInternal _SearchResponse_default_instance_;
class SearchResult;
struct SearchResultDefaultTypeInternal;
extern SearchResultDefaultTypeInternal _SearchResult_default_instance_;
}  // namespace search
PROTOBUF_NAMESPACE_OPEN
template<> ::search::SearchRequest* Arena::CreateMaybeMessage<::search::SearchRequest>(Arena*);
template<> ::search::SearchResponse* Arena::CreateMaybeMessage<::search::SearchResponse>(Arena*);
template<> ::search::SearchResult* Arena::CreateMaybeMessage<::search::SearchResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace search {

// ===================================================================

class SearchRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:search.SearchRequest) */ {
 public:
  inline SearchRequest() : SearchRequest(nullptr) {}
  ~SearchRequest() override;
  explicit PROTOBUF_CONSTEXPR SearchRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SearchRequest(const SearchRequest& from);
  SearchRequest(SearchRequest&& from) noexcept
    : SearchRequest() {
    *this = ::std::move(from);
  }

  inline SearchRequest& operator=(const SearchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchRequest& operator=(SearchRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SearchRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SearchRequest* internal_default_instance() {
    return reinterpret_cast<const SearchRequest*>(
               &_SearchRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SearchRequest& a, SearchRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SearchRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SearchRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SearchRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SearchRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SearchRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SearchRequest& from) {
    SearchRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "search.SearchRequest";
  }
  protected:
  explicit SearchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQueryFieldNumber = 1,
    kLimitFieldNumber = 2,
    kOffsetFieldNumber = 3,
    kEnableVectorSearchFieldNumber = 4,
  };
  // string query = 1;
  void clear_query();
  const std::string& query() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_query(ArgT0&& arg0, ArgT... args);
  std::string* mutable_query();
  PROTOBUF_NODISCARD std::string* release_query();
  void set_allocated_query(std::string* query);
  private:
  const std::string& _internal_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_query(const std::string& value);
  std::string* _internal_mutable_query();
  public:

  // int32 limit = 2;
  void clear_limit();
  int32_t limit() const;
  void set_limit(int32_t value);
  private:
  int32_t _internal_limit() const;
  void _internal_set_limit(int32_t value);
  public:

  // int32 offset = 3;
  void clear_offset();
  int32_t offset() const;
  void set_offset(int32_t value);
  private:
  int32_t _internal_offset() const;
  void _internal_set_offset(int32_t value);
  public:

  // bool enable_vector_search = 4;
  void clear_enable_vector_search();
  bool enable_vector_search() const;
  void set_enable_vector_search(bool value);
  private:
  bool _internal_enable_vector_search() const;
  void _internal_set_enable_vector_search(bool value);
  public:

  // @@protoc_insertion_point(class_scope:search.SearchRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr query_;
    int32_t limit_;
    int32_t offset_;
    bool enable_vector_search_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_search_2eproto;
};
// -------------------------------------------------------------------

class SearchResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:search.SearchResult) */ {
 public:
  inline SearchResult() : SearchResult(nullptr) {}
  ~SearchResult() override;
  explicit PROTOBUF_CONSTEXPR SearchResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SearchResult(const SearchResult& from);
  SearchResult(SearchResult&& from) noexcept
    : SearchResult() {
    *this = ::std::move(from);
  }

  inline SearchResult& operator=(const SearchResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchResult& operator=(SearchResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SearchResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const SearchResult* internal_default_instance() {
    return reinterpret_cast<const SearchResult*>(
               &_SearchResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SearchResult& a, SearchResult& b) {
    a.Swap(&b);
  }
  inline void Swap(SearchResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SearchResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SearchResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SearchResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SearchResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SearchResult& from) {
    SearchResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "search.SearchResult";
  }
  protected:
  explicit SearchResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageUrlsFieldNumber = 5,
    kUrlFieldNumber = 1,
    kTitleFieldNumber = 2,
    kSnippetFieldNumber = 3,
    kScoreFieldNumber = 4,
  };
  // repeated string image_urls = 5;
  int image_urls_size() const;
  private:
  int _internal_image_urls_size() const;
  public:
  void clear_image_urls();
  const std::string& image_urls(int index) const;
  std::string* mutable_image_urls(int index);
  void set_image_urls(int index, const std::string& value);
  void set_image_urls(int index, std::string&& value);
  void set_image_urls(int index, const char* value);
  void set_image_urls(int index, const char* value, size_t size);
  std::string* add_image_urls();
  void add_image_urls(const std::string& value);
  void add_image_urls(std::string&& value);
  void add_image_urls(const char* value);
  void add_image_urls(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& image_urls() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_image_urls();
  private:
  const std::string& _internal_image_urls(int index) const;
  std::string* _internal_add_image_urls();
  public:

  // string url = 1;
  void clear_url();
  const std::string& url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_url();
  PROTOBUF_NODISCARD std::string* release_url();
  void set_allocated_url(std::string* url);
  private:
  const std::string& _internal_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_url(const std::string& value);
  std::string* _internal_mutable_url();
  public:

  // string title = 2;
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string snippet = 3;
  void clear_snippet();
  const std::string& snippet() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_snippet(ArgT0&& arg0, ArgT... args);
  std::string* mutable_snippet();
  PROTOBUF_NODISCARD std::string* release_snippet();
  void set_allocated_snippet(std::string* snippet);
  private:
  const std::string& _internal_snippet() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_snippet(const std::string& value);
  std::string* _internal_mutable_snippet();
  public:

  // float score = 4;
  void clear_score();
  float score() const;
  void set_score(float value);
  private:
  float _internal_score() const;
  void _internal_set_score(float value);
  public:

  // @@protoc_insertion_point(class_scope:search.SearchResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> image_urls_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr url_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr snippet_;
    float score_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_search_2eproto;
};
// -------------------------------------------------------------------

class SearchResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:search.SearchResponse) */ {
 public:
  inline SearchResponse() : SearchResponse(nullptr) {}
  ~SearchResponse() override;
  explicit PROTOBUF_CONSTEXPR SearchResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SearchResponse(const SearchResponse& from);
  SearchResponse(SearchResponse&& from) noexcept
    : SearchResponse() {
    *this = ::std::move(from);
  }

  inline SearchResponse& operator=(const SearchResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchResponse& operator=(SearchResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SearchResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SearchResponse* internal_default_instance() {
    return reinterpret_cast<const SearchResponse*>(
               &_SearchResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SearchResponse& a, SearchResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SearchResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SearchResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SearchResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SearchResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SearchResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SearchResponse& from) {
    SearchResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "search.SearchResponse";
  }
  protected:
  explicit SearchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultsFieldNumber = 1,
    kTotalResultsFieldNumber = 2,
    kLatencyMsFieldNumber = 3,
  };
  // repeated .search.SearchResult results = 1;
  int results_size() const;
  private:
  int _internal_results_size() const;
  public:
  void clear_results();
  ::search::SearchResult* mutable_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::search::SearchResult >*
      mutable_results();
  private:
  const ::search::SearchResult& _internal_results(int index) const;
  ::search::SearchResult* _internal_add_results();
  public:
  const ::search::SearchResult& results(int index) const;
  ::search::SearchResult* add_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::search::SearchResult >&
      results() const;

  // int64 total_results = 2;
  void clear_total_results();
  int64_t total_results() const;
  void set_total_results(int64_t value);
  private:
  int64_t _internal_total_results() const;
  void _internal_set_total_results(int64_t value);
  public:

  // float latency_ms = 3;
  void clear_latency_ms();
  float latency_ms() const;
  void set_latency_ms(float value);
  private:
  float _internal_latency_ms() const;
  void _internal_set_latency_ms(float value);
  public:

  // @@protoc_insertion_point(class_scope:search.SearchResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::search::SearchResult > results_;
    int64_t total_results_;
    float latency_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_search_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SearchRequest

// string query = 1;
inline void SearchRequest::clear_query() {
  _impl_.query_.ClearToEmpty();
}
inline const std::string& SearchRequest::query() const {
  // @@protoc_insertion_point(field_get:search.SearchRequest.query)
  return _internal_query();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SearchRequest::set_query(ArgT0&& arg0, ArgT... args) {
 
 _impl_.query_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:search.SearchRequest.query)
}
inline std::string* SearchRequest::mutable_query() {
  std::string* _s = _internal_mutable_query();
  // @@protoc_insertion_point(field_mutable:search.SearchRequest.query)
  return _s;
}
inline const std::string& SearchRequest::_internal_query() const {
  return _impl_.query_.Get();
}
inline void SearchRequest::_internal_set_query(const std::string& value) {
  
  _impl_.query_.Set(value, GetArenaForAllocation());
}
inline std::string* SearchRequest::_internal_mutable_query() {
  
  return _impl_.query_.Mutable(GetArenaForAllocation());
}
inline std::string* SearchRequest::release_query() {
  // @@protoc_insertion_point(field_release:search.SearchRequest.query)
  return _impl_.query_.Release();
}
inline void SearchRequest::set_allocated_query(std::string* query) {
  if (query != nullptr) {
    
  } else {
    
  }
  _impl_.query_.SetAllocated(query, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.query_.IsDefault()) {
    _impl_.query_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:search.SearchRequest.query)
}

// int32 limit = 2;
inline void SearchRequest::clear_limit() {
  _impl_.limit_ = 0;
}
inline int32_t SearchRequest::_internal_limit() const {
  return _impl_.limit_;
}
inline int32_t SearchRequest::limit() const {
  // @@protoc_insertion_point(field_get:search.SearchRequest.limit)
  return _internal_limit();
}
inline void SearchRequest::_internal_set_limit(int32_t value) {
  
  _impl_.limit_ = value;
}
inline void SearchRequest::set_limit(int32_t value) {
  _internal_set_limit(value);
  // @@protoc_insertion_point(field_set:search.SearchRequest.limit)
}

// int32 offset = 3;
inline void SearchRequest::clear_offset() {
  _impl_.offset_ = 0;
}
inline int32_t SearchRequest::_internal_offset() const {
  return _impl_.offset_;
}
inline int32_t SearchRequest::offset() const {
  // @@protoc_insertion_point(field_get:search.SearchRequest.offset)
  return _internal_offset();
}
inline void SearchRequest::_internal_set_offset(int32_t value) {
  
  _impl_.offset_ = value;
}
inline void SearchRequest::set_offset(int32_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:search.SearchRequest.offset)
}

// bool enable_vector_search = 4;
inline void SearchRequest::clear_enable_vector_search() {
  _impl_.enable_vector_search_ = false;
}
inline bool SearchRequest::_internal_enable_vector_search() const {
  return _impl_.enable_vector_search_;
}
inline bool SearchRequest::enable_vector_search() const {
  // @@protoc_insertion_point(field_get:search.SearchRequest.enable_vector_search)
  return _internal_enable_vector_search();
}
inline void SearchRequest::_internal_set_enable_vector_search(bool value) {
  
  _impl_.enable_vector_search_ = value;
}
inline void SearchRequest::set_enable_vector_search(bool value) {
  _internal_set_enable_vector_search(value);
  // @@protoc_insertion_point(field_set:search.SearchRequest.enable_vector_search)
}

// -------------------------------------------------------------------

// SearchResult

// string url = 1;
inline void SearchResult::clear_url() {
  _impl_.url_.ClearToEmpty();
}
inline const std::string& SearchResult::url() const {
  // @@protoc_insertion_point(field_get:search.SearchResult.url)
  return _internal_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SearchResult::set_url(ArgT0&& arg0, ArgT... args) {
 
 _impl_.url_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:search.SearchResult.url)
}
inline std::string* SearchResult::mutable_url() {
  std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:search.SearchResult.url)
  return _s;
}
inline const std::string& SearchResult::_internal_url() const {
  return _impl_.url_.Get();
}
inline void SearchResult::_internal_set_url(const std::string& value) {
  
  _impl_.url_.Set(value, GetArenaForAllocation());
}
inline std::string* SearchResult::_internal_mutable_url() {
  
  return _impl_.url_.Mutable(GetArenaForAllocation());
}
inline std::string* SearchResult::release_url() {
  // @@protoc_insertion_point(field_release:search.SearchResult.url)
  return _impl_.url_.Release();
}
inline void SearchResult::set_allocated_url(std::string* url) {
  if (url != nullptr) {
    
  } else {
    
  }
  _impl_.url_.SetAllocated(url, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:search.SearchResult.url)
}

// string title = 2;
inline void SearchResult::clear_title() {
  _impl_.title_.ClearToEmpty();
}
inline const std::string& SearchResult::title() const {
  // @@protoc_insertion_point(field_get:search.SearchResult.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SearchResult::set_title(ArgT0&& arg0, ArgT... args) {
 
 _impl_.title_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:search.SearchResult.title)
}
inline std::string* SearchResult::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:search.SearchResult.title)
  return _s;
}
inline const std::string& SearchResult::_internal_title() const {
  return _impl_.title_.Get();
}
inline void SearchResult::_internal_set_title(const std::string& value) {
  
  _impl_.title_.Set(value, GetArenaForAllocation());
}
inline std::string* SearchResult::_internal_mutable_title() {
  
  return _impl_.title_.Mutable(GetArenaForAllocation());
}
inline std::string* SearchResult::release_title() {
  // @@protoc_insertion_point(field_release:search.SearchResult.title)
  return _impl_.title_.Release();
}
inline void SearchResult::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  _impl_.title_.SetAllocated(title, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.title_.IsDefault()) {
    _impl_.title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:search.SearchResult.title)
}

// string snippet = 3;
inline void SearchResult::clear_snippet() {
  _impl_.snippet_.ClearToEmpty();
}
inline const std::string& SearchResult::snippet() const {
  // @@protoc_insertion_point(field_get:search.SearchResult.snippet)
  return _internal_snippet();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SearchResult::set_snippet(ArgT0&& arg0, ArgT... args) {
 
 _impl_.snippet_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:search.SearchResult.snippet)
}
inline std::string* SearchResult::mutable_snippet() {
  std::string* _s = _internal_mutable_snippet();
  // @@protoc_insertion_point(field_mutable:search.SearchResult.snippet)
  return _s;
}
inline const std::string& SearchResult::_internal_snippet() const {
  return _impl_.snippet_.Get();
}
inline void SearchResult::_internal_set_snippet(const std::string& value) {
  
  _impl_.snippet_.Set(value, GetArenaForAllocation());
}
inline std::string* SearchResult::_internal_mutable_snippet() {
  
  return _impl_.snippet_.Mutable(GetArenaForAllocation());
}
inline std::string* SearchResult::release_snippet() {
  // @@protoc_insertion_point(field_release:search.SearchResult.snippet)
  return _impl_.snippet_.Release();
}
inline void SearchResult::set_allocated_snippet(std::string* snippet) {
  if (snippet != nullptr) {
    
  } else {
    
  }
  _impl_.snippet_.SetAllocated(snippet, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.snippet_.IsDefault()) {
    _impl_.snippet_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:search.SearchResult.snippet)
}

// float score = 4;
inline void SearchResult::clear_score() {
  _impl_.score_ = 0;
}
inline float SearchResult::_internal_score() const {
  return _impl_.score_;
}
inline float SearchResult::score() const {
  // @@protoc_insertion_point(field_get:search.SearchResult.score)
  return _internal_score();
}
inline void SearchResult::_internal_set_score(float value) {
  
  _impl_.score_ = value;
}
inline void SearchResult::set_score(float value) {
  _internal_set_score(value);
  // @@protoc_insertion_point(field_set:search.SearchResult.score)
}

// repeated string image_urls = 5;
inline int SearchResult::_internal_image_urls_size() const {
  return _impl_.image_urls_.size();
}
inline int SearchResult::image_urls_size() const {
  return _internal_image_urls_size();
}
inline void SearchResult::clear_image_urls() {
  _impl_.image_urls_.Clear();
}
inline std::string* SearchResult::add_image_urls() {
  std::string* _s = _internal_add_image_urls();
  // @@protoc_insertion_point(field_add_mutable:search.SearchResult.image_urls)
  return _s;
}
inline const std::string& SearchResult::_internal_image_urls(int index) const {
  return _impl_.image_urls_.Get(index);
}
inline const std::string& SearchResult::image_urls(int index) const {
  // @@protoc_insertion_point(field_get:search.SearchResult.image_urls)
  return _internal_image_urls(index);
}
inline std::string* SearchResult::mutable_image_urls(int index) {
  // @@protoc_insertion_point(field_mutable:search.SearchResult.image_urls)
  return _impl_.image_urls_.Mutable(index);
}
inline void SearchResult::set_image_urls(int index, const std::string& value) {
  _impl_.image_urls_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:search.SearchResult.image_urls)
}
inline void SearchResult::set_image_urls(int index, std::string&& value) {
  _impl_.image_urls_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:search.SearchResult.image_urls)
}
inline void SearchResult::set_image_urls(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.image_urls_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:search.SearchResult.image_urls)
}
inline void SearchResult::set_image_urls(int index, const char* value, size_t size) {
  _impl_.image_urls_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:search.SearchResult.image_urls)
}
inline std::string* SearchResult::_internal_add_image_urls() {
  return _impl_.image_urls_.Add();
}
inline void SearchResult::add_image_urls(const std::string& value) {
  _impl_.image_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:search.SearchResult.image_urls)
}
inline void SearchResult::add_image_urls(std::string&& value) {
  _impl_.image_urls_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:search.SearchResult.image_urls)
}
inline void SearchResult::add_image_urls(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.image_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:search.SearchResult.image_urls)
}
inline void SearchResult::add_image_urls(const char* value, size_t size) {
  _impl_.image_urls_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:search.SearchResult.image_urls)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
SearchResult::image_urls() const {
  // @@protoc_insertion_point(field_list:search.SearchResult.image_urls)
  return _impl_.image_urls_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
SearchResult::mutable_image_urls() {
  // @@protoc_insertion_point(field_mutable_list:search.SearchResult.image_urls)
  return &_impl_.image_urls_;
}

// -------------------------------------------------------------------

// SearchResponse

// repeated .search.SearchResult results = 1;
inline int SearchResponse::_internal_results_size() const {
  return _impl_.results_.size();
}
inline int SearchResponse::results_size() const {
  return _internal_results_size();
}
inline void SearchResponse::clear_results() {
  _impl_.results_.Clear();
}
inline ::search::SearchResult* SearchResponse::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:search.SearchResponse.results)
  return _impl_.results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::search::SearchResult >*
SearchResponse::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:search.SearchResponse.results)
  return &_impl_.results_;
}
inline const ::search::SearchResult& SearchResponse::_internal_results(int index) const {
  return _impl_.results_.Get(index);
}
inline const ::search::SearchResult& SearchResponse::results(int index) const {
  // @@protoc_insertion_point(field_get:search.SearchResponse.results)
  return _internal_results(index);
}
inline ::search::SearchResult* SearchResponse::_internal_add_results() {
  return _impl_.results_.Add();
}
inline ::search::SearchResult* SearchResponse::add_results() {
  ::search::SearchResult* _add = _internal_add_results();
  // @@protoc_insertion_point(field_add:search.SearchResponse.results)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::search::SearchResult >&
SearchResponse::results() const {
  // @@protoc_insertion_point(field_list:search.SearchResponse.results)
  return _impl_.results_;
}

// int64 total_results = 2;
inline void SearchResponse::clear_total_results() {
  _impl_.total_results_ = int64_t{0};
}
inline int64_t SearchResponse::_internal_total_results() const {
  return _impl_.total_results_;
}
inline int64_t SearchResponse::total_results() const {
  // @@protoc_insertion_point(field_get:search.SearchResponse.total_results)
  return _internal_total_results();
}
inline void SearchResponse::_internal_set_total_results(int64_t value) {
  
  _impl_.total_results_ = value;
}
inline void SearchResponse::set_total_results(int64_t value) {
  _internal_set_total_results(value);
  // @@protoc_insertion_point(field_set:search.SearchResponse.total_results)
}

// float latency_ms = 3;
inline void SearchResponse::clear_latency_ms() {
  _impl_.latency_ms_ = 0;
}
inline float SearchResponse::_internal_latency_ms() const {
  return _impl_.latency_ms_;
}
inline float SearchResponse::latency_ms() const {
  // @@protoc_insertion_point(field_get:search.SearchResponse.latency_ms)
  return _internal_latency_ms();
}
inline void SearchResponse::_internal_set_latency_ms(float value) {
  
  _impl_.latency_ms_ = value;
}
inline void SearchResponse::set_latency_ms(float value) {
  _internal_set_latency_ms(value);
  // @@protoc_insertion_point(field_set:search.SearchResponse.latency_ms)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace search

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_search_2eproto
