// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.21.12
// source: inference.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "inference";

export interface DescribeImageRequest {
  imageData: Buffer;
  prompt: string;
}

export interface DescribeImageResponse {
  description: string;
}

export interface ChatRequest {
  prompt: string;
  history: string[];
  /** Optional image data for multimodal query context */
  imageData: Buffer;
}

export interface ChatResponse {
  token: string;
  done: boolean;
}

function createBaseDescribeImageRequest(): DescribeImageRequest {
  return { imageData: Buffer.alloc(0), prompt: "" };
}

export const DescribeImageRequest: MessageFns<DescribeImageRequest> = {
  encode(message: DescribeImageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.imageData.length !== 0) {
      writer.uint32(10).bytes(message.imageData);
    }
    if (message.prompt !== "") {
      writer.uint32(18).string(message.prompt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DescribeImageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDescribeImageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.imageData = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.prompt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DescribeImageRequest {
    return {
      imageData: isSet(object.imageData)
        ? Buffer.from(bytesFromBase64(object.imageData))
        : isSet(object.image_data)
        ? Buffer.from(bytesFromBase64(object.image_data))
        : Buffer.alloc(0),
      prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
    };
  },

  toJSON(message: DescribeImageRequest): unknown {
    const obj: any = {};
    if (message.imageData.length !== 0) {
      obj.imageData = base64FromBytes(message.imageData);
    }
    if (message.prompt !== "") {
      obj.prompt = message.prompt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DescribeImageRequest>, I>>(base?: I): DescribeImageRequest {
    return DescribeImageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DescribeImageRequest>, I>>(object: I): DescribeImageRequest {
    const message = createBaseDescribeImageRequest();
    message.imageData = object.imageData ?? Buffer.alloc(0);
    message.prompt = object.prompt ?? "";
    return message;
  },
};

function createBaseDescribeImageResponse(): DescribeImageResponse {
  return { description: "" };
}

export const DescribeImageResponse: MessageFns<DescribeImageResponse> = {
  encode(message: DescribeImageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.description !== "") {
      writer.uint32(10).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DescribeImageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDescribeImageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DescribeImageResponse {
    return { description: isSet(object.description) ? globalThis.String(object.description) : "" };
  },

  toJSON(message: DescribeImageResponse): unknown {
    const obj: any = {};
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DescribeImageResponse>, I>>(base?: I): DescribeImageResponse {
    return DescribeImageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DescribeImageResponse>, I>>(object: I): DescribeImageResponse {
    const message = createBaseDescribeImageResponse();
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseChatRequest(): ChatRequest {
  return { prompt: "", history: [], imageData: Buffer.alloc(0) };
}

export const ChatRequest: MessageFns<ChatRequest> = {
  encode(message: ChatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.prompt !== "") {
      writer.uint32(10).string(message.prompt);
    }
    for (const v of message.history) {
      writer.uint32(18).string(v!);
    }
    if (message.imageData.length !== 0) {
      writer.uint32(26).bytes(message.imageData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.prompt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.history.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.imageData = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatRequest {
    return {
      prompt: isSet(object.prompt) ? globalThis.String(object.prompt) : "",
      history: globalThis.Array.isArray(object?.history) ? object.history.map((e: any) => globalThis.String(e)) : [],
      imageData: isSet(object.imageData)
        ? Buffer.from(bytesFromBase64(object.imageData))
        : isSet(object.image_data)
        ? Buffer.from(bytesFromBase64(object.image_data))
        : Buffer.alloc(0),
    };
  },

  toJSON(message: ChatRequest): unknown {
    const obj: any = {};
    if (message.prompt !== "") {
      obj.prompt = message.prompt;
    }
    if (message.history?.length) {
      obj.history = message.history;
    }
    if (message.imageData.length !== 0) {
      obj.imageData = base64FromBytes(message.imageData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatRequest>, I>>(base?: I): ChatRequest {
    return ChatRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatRequest>, I>>(object: I): ChatRequest {
    const message = createBaseChatRequest();
    message.prompt = object.prompt ?? "";
    message.history = object.history?.map((e) => e) || [];
    message.imageData = object.imageData ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseChatResponse(): ChatResponse {
  return { token: "", done: false };
}

export const ChatResponse: MessageFns<ChatResponse> = {
  encode(message: ChatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    if (message.done !== false) {
      writer.uint32(16).bool(message.done);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.done = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatResponse {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      done: isSet(object.done) ? globalThis.Boolean(object.done) : false,
    };
  },

  toJSON(message: ChatResponse): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.done !== false) {
      obj.done = message.done;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatResponse>, I>>(base?: I): ChatResponse {
    return ChatResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatResponse>, I>>(object: I): ChatResponse {
    const message = createBaseChatResponse();
    message.token = object.token ?? "";
    message.done = object.done ?? false;
    return message;
  },
};

export type InferenceServiceService = typeof InferenceServiceService;
export const InferenceServiceService = {
  describeImage: {
    path: "/inference.InferenceService/DescribeImage" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DescribeImageRequest): Buffer => Buffer.from(DescribeImageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DescribeImageRequest => DescribeImageRequest.decode(value),
    responseSerialize: (value: DescribeImageResponse): Buffer =>
      Buffer.from(DescribeImageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DescribeImageResponse => DescribeImageResponse.decode(value),
  },
  /** Streaming response for real-time token generation */
  chat: {
    path: "/inference.InferenceService/Chat" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: ChatRequest): Buffer => Buffer.from(ChatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ChatRequest => ChatRequest.decode(value),
    responseSerialize: (value: ChatResponse): Buffer => Buffer.from(ChatResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatResponse => ChatResponse.decode(value),
  },
} as const;

export interface InferenceServiceServer extends UntypedServiceImplementation {
  describeImage: handleUnaryCall<DescribeImageRequest, DescribeImageResponse>;
  /** Streaming response for real-time token generation */
  chat: handleServerStreamingCall<ChatRequest, ChatResponse>;
}

export interface InferenceServiceClient extends Client {
  describeImage(
    request: DescribeImageRequest,
    callback: (error: ServiceError | null, response: DescribeImageResponse) => void,
  ): ClientUnaryCall;
  describeImage(
    request: DescribeImageRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DescribeImageResponse) => void,
  ): ClientUnaryCall;
  describeImage(
    request: DescribeImageRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DescribeImageResponse) => void,
  ): ClientUnaryCall;
  /** Streaming response for real-time token generation */
  chat(request: ChatRequest, options?: Partial<CallOptions>): ClientReadableStream<ChatResponse>;
  chat(request: ChatRequest, metadata?: Metadata, options?: Partial<CallOptions>): ClientReadableStream<ChatResponse>;
}

export const InferenceServiceClient = makeGenericClientConstructor(
  InferenceServiceService,
  "inference.InferenceService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): InferenceServiceClient;
  service: typeof InferenceServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
